---
title: "Principal Component Analysis (PCA)"
author: "Conrado Eiroa-Solans"
output: pdf_document
---

```{r}
#New data
data <- mtcars 
data$vs <- NULL #remove data we won't use
data$am <- NULL


#Correlation matrix
library(corrplot)
cor(data) #normal correlation matrix
corrplot(cor(data), order="hclust") 
```


Principal component analysis:
Reduce variables to a smaller number of Principal Components (correspond to a linear combination of the originals)
```{r}
#Principal component analysis
data.pca <- prcomp(data, center = TRUE, scale = TRUE) #  analysis with z-scores
summary(data.pca)
```


```{r}
#Visualize
library(factoextra)

#Extract components (scree plot)
fviz_eig(data.pca,choice = c("variance")) # % variances explained by component

#Interpret
fviz_pca_var(data.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )

#Visualize how individual dots relate to the axes
fviz_pca_biplot(data.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )

```


